# Generated by Django 6.0.2 on 2026-02-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อหนังสือ')),
                ('author', models.CharField(max_length=200, verbose_name='ผู้แต่ง')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='รหัส ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('copy_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='รหัสบาร์โค้ด (Copy ID)')),
                ('status', models.CharField(choices=[('available', 'Available (พร้อมให้ยืม)'), ('borrowed', 'Borrowed (ถูกยืม)'), ('lost', 'Lost/Damaged (ชำรุด/สูญหาย)'), ('maintenance', 'Maintenance (ซ่อมบำรุง)')], default='available', max_length=20, verbose_name='สถานะ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='ชื่อหนังสือ')),
            ],
        ),
    ]
