# Generated by Django 6.0.2 on 2026-02-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยืม')),
                ('due_date', models.DateTimeField(verbose_name='กำหนดคืน')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืนจริง')),
                ('status', models.CharField(choices=[('borrowed', 'กำลังยืม'), ('returned', 'คืนแล้ว'), ('overdue', 'เกินกำหนด')], default='borrowed', max_length=20, verbose_name='สถานะการยืม')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='books.bookcopy', verbose_name='เล่มที่ยืม (บาร์โค้ด)')),
            ],
        ),
    ]
